---
settings:
  name: BlueXP Workload Factory for AWS
  platform: cloud
  search: workload-setup-admin,workload-fsx-ontap,workload-databases,workload-vmware,workload-genai,workload-family
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
    lipi_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Toda a documentação do Workload Factory
    url: "/index.html"
